locksidian-primary:
  image: registry.gitlab.com/locksidian/locksidian:dev
  environment:
    - EXTERNAL_NODE=${EXTERNAL_NODE}
  ports:
    - 8080:8080
  working_dir: /app
  entrypoint: /bin/bash -c "/app/locksidian -d 0.0.0.0:8080 -e $${EXTERNAL_NODE:-127.0.0.1:8080} || /app/locksidian --identity $$(/app/locksidian --identity-new 4096) -d 0.0.0.0:8080 -e $${EXTERNAL_NODE:-127.0.0.1:8080}"

locksidian-node-alpha:
  image: registry.gitlab.com/locksidian/locksidian:dev
  environment:
    - EXTERNAL_NODE=${EXTERNAL_NODE}
  ports:
    - 64444:64444
  links:
    - locksidian-primary
  working_dir: /app
  entrypoint: /bin/bash -c "/app/locksidian -d 0.0.0.0:64444 -e $${EXTERNAL_NODE:-locksidian-primary:8080} || /app/locksidian --identity $$(/app/locksidian --identity-new 4096) -d 0.0.0.0:64444 $${EXTERNAL_NODE:-locksidian-primary:8080}"

locksidian-node-beta:
  image: registry.gitlab.com/locksidian/locksidian:dev
  environment:
    - EXTERNAL_NODE=${EXTERNAL_NODE}
  ports:
    - 64445:64445
  links:
    - locksidian-primary
  working_dir: /app
  entrypoint: /bin/bash -c "/app/locksidian -d 0.0.0.0:64445 -e $${EXTERNAL_NODE:-locksidian-primary:8080} || /app/locksidian --identity $$(/app/locksidian --identity-new 4096) -d 0.0.0.0:64445 $${EXTERNAL_NODE:-locksidian-primary:8080}"
locksidian-node-gamma:
  image: registry.gitlab.com/locksidian/locksidian:dev
  environment:
    - EXTERNAL_NODE=${EXTERNAL_NODE}
  ports:
    - 64446:64446
  links:
    - locksidian-primary
  working_dir: /app
  entrypoint:  /bin/bash -c "/app/locksidian -d 0.0.0.0:64446 -e $${EXTERNAL_NODE:-locksidian-primary:8080} || /app/locksidian --identity $$(/app/locksidian --identity-new 4096) -d 0.0.0.0:64446 $${EXTERNAL_NODE:-locksidian-primary:8080}"

locksidian-node-epsilon:
  image: registry.gitlab.com/locksidian/locksidian:dev
  environment:
    - EXTERNAL_NODE=${EXTERNAL_NODE}
  ports:
    - 64447:64447
  links:
    - locksidian-primary
  working_dir: /app
  entrypoint: /bin/bash -c "/app/locksidian -d 0.0.0.0:64447 -e $${EXTERNAL_NODE:-locksidian-primary:8080} || /app/locksidian --identity $$(/app/locksidian --identity-new 4096) -d 0.0.0.0:64447 $${EXTERNAL_NODE:-locksidian-primary:8080}"
